#db.host=prog3-labs-1inf30.cj4sudicbpxk.us-east-1.rds.amazonaws.com
#db.schema=shiligama
#db.user=admin
#db.password=labs1inf3020261
#db.port=3306
db.host=programacion3parcial.cwulcxw2eedn.us-east-1.rds.amazonaws.com
db.schema=shiligama?useSSL=false&allowPublicKeyRetrieval=true
db.user=admin
db.password=pacoflaco123
db.port=3306