db.host=programacion3.ci3waddo5vya.us-east-1.rds.amazonaws.com
db.schema=shiligama?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima&useServerPrepStmts=false
db.user=admin
db.password=pacoflaco123
db.port=3306
#db.host=programacion3parcial.cwulcxw2eedn.us-east-1.rds.amazonaws.com
#db.schema=shiligama?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima&useServerPrepStmts=false
#db.user=admin
#db.password=pacoflaco123
#db.port=3306
